const programmingLanguages = [
  { name: 'JavaScript', color: '#F7DF1E', textColor: '#000', symbol: 'JS' },
  { name: 'Python', image: '/icons/python.png', color: '#3776AB', textColor: '#fff' },
  { name: 'TypeScript', color: '#3178C6', textColor: '#fff', symbol: 'TS' },
  { name: 'PHP', color: '#777BB4', textColor: '#fff', symbol: 'PHP' },
  { name: 'Java', color: '#5382A1', textColor: '#fff', symbol: 'Java' },
  { name: 'Dart', color: '#0175C2', textColor: '#fff', symbol: 'Dart' },
  // 🖥️ Web Development
  {
    name: 'ReactJS',
    image: '/icons/reactjs.png',
    color: '#61DAFB',
    textColor: '#000',
  },
  {
    name: 'Next.js',
    image: '/icons/next.png',
    color: '#FFFFFF',
    textColor: '#000',
  },
  {
    name: 'Angular',
    image: '/icons/angular.png',
    color: '#DD0031',
    textColor: '#fff',
  },
  {
    name: 'Node.js',
    image: '/icons/node.png',
    color: '#3C873A',
    textColor: '#fff',
  },
  {
    name: 'Express',
    image: '/icons/express.png',
    color: '#CCCCCC',
    textColor: '#000',
  },
  {
    name: 'Spring Boot',
    image: '/icons/spring.png',
    color: '#6DB33F',
    textColor: '#fff',
  },
  {
    name: 'Redux',
    image: '/icons/redux.png',
    color: '#764ABC',
    textColor: '#fff',
  },

  // 📱 Mobile Development
  {
    name: 'Expo',
    image: '/icons/expo.png',
    color: '#FFFFFF',
    textColor: '#fff',
  },
  {
    name: 'React Native',
    image: '/icons/reactnative.png',
    color: '#61DAFB',
    textColor: '#000',
  },
  {
    name: 'Flutter',
    color: '#02569B',
    textColor: '#fff',
    symbol: 'Fl',
  },

  // 🛢️ Databases
  {
    name: 'Redis',
    image: '/icons/redis.png',
    color: '#DC382D',
    textColor: '#fff',
  },
  {
    name: 'MySQL',
    image: '/icons/mysql.png',
    color: '#00758F',
    textColor: '#fff',
  },
  {
    name: 'MongoDB',
    image: '/icons/mongo.png',
    color: '#47A248',
    textColor: '#fff',
  },
  {
    name: 'SQLite',
    image: '/icons/sqlite.png',
    color: '#FFFFFF',
    textColor: '#fff',
  },

  // ⚙️ Tools / Others
  {
    name: 'Docker',
    image: '/icons/docker.png',
    color: '#2496ED',
    textColor: '#fff',
  },
  { name: 'Git', image: '/icons/git.png', color: '#F1502F', textColor: '#000' },
  {
    name: 'Linux',
    image: '/icons/linux.png',
    color: '#FCC624',
    textColor: '#000',
  },
  {
    name: 'Figma',
    image: '/icons/figma.png',
    color: '#F24E1E',
    textColor: '#fff',
  },
  {
    name: 'Laravel',
    image: '/icons/laravel.png',
    color: '#FF2D20',
    textColor: '#fff',
  },
  {
    name: 'NestJS',
    image: '/icons/nest.js.png',
    color: '#E0234E',
    textColor: '#fff',
  },
  {
    name: 'PostgreSQL',
    image: '/icons/postgresSQL.png',
    color: '#336791',
    textColor: '#fff',
  },
];

const categories = [
  {
    title: 'Frontend development',
    items: [
      'React',
      'Next.js',
      'Angular',
      'TypeScript',
      'JavaScript',
      'Tailwind CSS',
      'Framer Motion',
      'Redux',
    ],
  },
  {
    title: 'Backend development',
    items: [
      'Node.js',
      'Express',
      'NestJS',
      'MongoDB',
      'PHP',
      'Laravel',
      'Java',
      'Spring Boot',
      'Redis',
      'MySQL',
      'SQLite',
      'PostgreSQL',
    ],
  },
  {
    title: 'Mobile development',
    items: ['React Native', 'Expo', 'Flutter', 'Dart'],
  },
  {
    title: 'Other skills',
    items: [
      'Git',
      'Docker',
      'GraphQL',
      'RESTful APIs',
      'Socket.IO',
      'Linux',
      'Figma',
    ],
  },
];
const projects = [
  {
    name: 'TESSAM POS',
    intro:
      'A full-stack retail management platform developed as part of a larger ecosystem for managing operations across multiple malls and stores. The system combines a desktop/web administration platform for centralized monitoring with a React Native mobile POS application used by sellers for day-to-day store operations.',
    points: [
      'Built a cross-platform mobile POS application with React Native, enabling barcode scanning, instant checkout, and digital receipt generation.',
      'Developed desktop/web administrative dashboards for real-time tracking of multi-store sales, inventory, and staff operations.',
      'Designed scalable RESTful backend services and MongoDB data models supporting multi-mall retail workflows.',
      'Implemented role-based access control, integrated loyalty programs, and multi-payment processing.',
      'Created modular, responsive UI design systems from Figma prototypes with NativeWind.',
    ],
    images: [
      '/tessam/1.png',
      '/tessam/2.png',
      '/tessam/3.png',
      '/tessam/4.png',
      '/tessam/5.png',
      '/tessam/6.png',
    ],
    techStack: [
      { name: 'reactjs', image: '/icons/reactjs.png' },
      { name: 'nodejs', image: '/icons/node.png' },
      { name: 'express', image: '/icons/express.png' },
      { name: 'mongodb', image: '/icons/mongo.png' },
    ],
    link: 'https://tessam.netlify.app/',
    logo: '/logos/tessam.png',
    color: '#787878',
    created: 'July 2024',
  },
  {
    name: 'VerticCity',
    intro:
      'A full-stack mobile marketplace platform developed for a startup focused on promoting and expanding green spaces. The application connects plant sellers, buyers, and administrators through a multi-actor ecosystem combining e-commerce, content publishing, real-time communication, and operational analytics.',
    points: [
      'Built an end-to-end mobile marketplace with React Native and Zustand for plant browsing, filtering, and order tracking.',
      'Developed seller storefronts for inventory management, pricing, plant listings, and delivery status updates.',
      'Implemented real-time messaging and push notifications between buyers and sellers via WebSockets.',
      'Engineered an educational blogging CMS allowing sellers to publish plant-care guides and boost visibility.',
      'Built administrative analytics dashboards and scalable Node.js/Express REST APIs with MongoDB.',
    ],
    images: ['/verticCity/1.jpg', '/verticCity/2.jpg'],
    techStack: [
      { name: 'reactjs', image: '/icons/reactjs.png' },
      { name: 'nodejs', image: '/icons/node.png' },
      { name: 'express', image: '/icons/express.png' },
      { name: 'mongodb', image: '/icons/mongo.png' },
    ],
    link: 'https://drive.google.com/file/d/1O9eKu7O7xh7F00i_vEm05Z83ptAZj9Ah/view?usp=sharing',
    logo: '/logos/verticcity.png',
    color: '#7be89f',
    created: 'July 2024',
  },
  {
    name: 'NexoManager',
    intro:
      'A full-stack restaurant management platform developed for Nexo Pizza to centralize inventory, purchasing, and staff operations. The system provides role-specific workflows for staff, managers, and administrators, enabling real-time coordination of stock activities and purchasing processes.',
    points: [
      'Built a full-stack stock and restaurant management platform with Next.js, TypeScript, and shadcn/ui.',
      'Engineered automated inventory workflows for ingredient tracking, supply requests, and stock depletion.',
      'Implemented purchase approval pipelines with multi-role access control for staff, managers, and admins.',
      'Integrated real-time live synchronization across active sessions via WebSockets and TanStack Query.',
      'Containerized the entire platform using Docker and deployed with Node.js/Express backend APIs.',
    ],
    images: [
      '/nexo/mockup.png',
      '/nexo/1.png',
      '/nexo/2.png',
      '/nexo/3.png',
      '/nexo/4.png',
      '/nexo/5.png',
    ],
    techStack: [
      { name: 'nextjs', image: '/icons/next.png' },
      { name: 'nodejs', image: '/icons/node.png' },
      { name: 'express', image: '/icons/express.png' },
      { name: 'mongodb', image: '/icons/mongo.png' },
    ],
    link: 'https://nexo-manager.netlify.app/',
    logo: '/logos/nexo.png',
    color: '#F24E1E',
    created: 'July 2024',
  },
  {
    name: 'Nova Healthcare',
    intro:
      'A full-stack mobile healthcare platform designed to centralize appointment management and connect patients, doctors, and administrators through role-specific workflows. The platform streamlines the complete appointment lifecycle, from booking and availability management to confirmation and administrative oversight.',
    points: [
      'Developed a cross-platform mobile healthcare app with React Native, TypeScript, and Redux Toolkit.',
      'Engineered end-to-end appointment scheduling, status tracking, and doctor availability management.',
      'Implemented role-based workflows and portals for patients, doctors, and clinic administrators.',
      'Designed structured PostgreSQL schemas and relational data models for medical bookings and user profiles.',
      'Built high-performance REST APIs with Node.js and Express for synchronized scheduling operations.',
    ],
    images: ['/novadoc/1.png', '/novadoc/2.png'],
    techStack: [
      { name: 'react native', image: '/icons/reactnative.png' },
      { name: 'nodejs', image: '/icons/node.png' },
      { name: 'express', image: '/icons/express.png' },
      { name: 'mongodb', image: '/icons/mongo.png' },
    ],
    link: 'https://nova-app.netlify.app/',
    logo: '/logos/nova.png',
    color: '#dda9f0',
    created: 'July 2024',
  },
  {
    name: 'Bubble',
    intro:
      'A full-stack kindergarten management platform built to centralize child, class, attendance, scheduling, and parent–teacher workflows. Developed with Angular, Spring Boot, and PostgreSQL.',
    points: [
      'Managed child enrollment, class assignments, attendance, and daily records.',
      'Built activity and event scheduling for lessons and daily programs.',
      'Implemented parent–teacher communication for updates and notes.',
      'Developed an admin dashboard for staff, classes, capacity, and operational monitoring.',
      'Built REST APIs with Spring Boot and structured relational data models with PostgreSQL.',
    ],
    images: [
      '/bubble/1.png',
      '/bubble/2.png',
      '/bubble/3.png',
      '/bubble/4.png',
      '/bubble/5.png',
      '/bubble/6.png',
    ],
    techStack: [
      { name: 'Angular', image: '/icons/angular.png' },
      { name: 'Spring Boot', image: '/icons/spring.png' },
      { name: 'PostgreSQL', image: '/icons/postgresSQL.png' },
    ],
    link: '#',
    logo: '/logos/bubble.png',
    color: '#99CCD3',
    created: '2026',
  },
  {
    name: 'Madar',
    intro:
      'A high-performance corporate website developed for Madar, one of Algeria’s major industrial groups, showcasing its portfolio, subsidiaries, history, and corporate activities through a modern digital experience.',
    points: [
      'Built with Next.js, Tailwind CSS, React Motion, and SEO optimization.',
      'Developed a modern, responsive interface with Next.js and Tailwind CSS across desktop, tablet, and mobile.',
      'Implemented interactive animations and transitions using React Motion for a polished user experience.',
      'Built structured sections showcasing the group\'s companies, investments, history, and achievements.',
      'Implemented SEO best practices, including optimized metadata, page structure, and search-engine-friendly content.',
      'Optimized rendering and page structure for fast loading, smooth navigation, and discoverability.',
      'Developed reusable UI components to maintain a consistent and scalable frontend architecture.',
    ],
    images: [
      '/madar/1.png',
      '/madar/2.png',
      '/madar/3.png',
      '/madar/4.png',
      '/madar/5.png',
      '/madar/6.png',
      '/madar/7.png',
    ],
    techStack: [
      { name: 'Next.js', image: '/icons/next.png' },
    ],
    link: '#',
    logo: '/logos/madar.png',
    color: '#1E3A8A',
    created: '2025',
  },
  {
    name: 'Kalam',
    intro:
      'A full-stack document editing platform built around a rich-text writing experience, combining structured document management with AI-assisted writing and content modification.',
    points: [
      'Built with Next.js, Laravel, PostgreSQL, Tiptap, and Google Gemini AI.',
      'Built a rich-text editor with Tiptap, supporting formatting, lists, tables, code blocks, and structured document content.',
      'Developed a document management system for creating, editing, organizing, saving, and exporting writing projects.',
      'Integrated Google Gemini AI to generate content, rewrite text, modify existing content, and assist users directly within the editor.',
      'Developed a Next.js SPA interface for a responsive and fluid writing experience.',
      'Built secure backend APIs with Laravel for authentication, document management, file uploads, and persistent data operations.',
      'Designed PostgreSQL data models for users, documents, and application data.',
      'Integrated frontend and backend workflows to support real-time-feeling editing and saving experiences.',
    ],
    images: [
      '/kalam/1.png',
      '/kalam/2.png',
      '/kalam/3.png',
      '/kalam/4.png',
      '/kalam/5.png',
      '/kalam/6.png',
      '/kalam/7.png',
    ],
    techStack: [
      { name: 'Next.js', image: '/icons/next.png' },
      { name: 'Laravel', image: '/icons/laravel.png' },
      { name: 'PostgreSQL', image: '/icons/postgresSQL.png' },
    ],
    link: '#',
    logo: '/logos/kalam.png',
    color: '#66C6FF',
    created: '2026',
  },
  {
    name: 'EcoSmart',
    intro:
      'A full-stack e-commerce management platform designed to centralize sales, inventory, order processing, and business analytics through a scalable enterprise architecture.',
    points: [
      'Built with Next.js, TypeScript, Tailwind CSS, shadcn/ui, Spring Boot, and PostgreSQL.',
      'Developed dashboards for sales analytics, product performance, and inventory trends.',
      'Implemented inventory management for stock levels, incoming shipments, and low-stock monitoring.',
      'Built end-to-end order management workflows, from order placement through processing and shipping status.',
      'Developed responsive and reusable interfaces with Next.js, Tailwind CSS, and shadcn/ui.',
      'Built secure REST APIs and business logic with Spring Boot.',
      'Designed relational PostgreSQL data models for products, inventory, orders, and sales operations.',
      'Structured the platform to support scalable e-commerce and business management workflows.',
    ],
    images: [
      '/ecosmart/1.png',
      '/ecosmart/2.png',
      '/ecosmart/3.png',
      '/ecosmart/4.png',
      '/ecosmart/5.png',
      '/ecosmart/6.png',
      '/ecosmart/7.png',
    ],
    techStack: [
      { name: 'Next.js', image: '/icons/next.png' },
      { name: 'Spring Boot', image: '/icons/spring.png' },
      { name: 'PostgreSQL', image: '/icons/postgresSQL.png' },
    ],
    link: '#',
    logo: '/logos/ecosmart.jpg',
    color: '#BCD1FF',
    created: '2026',
  },
  {
    name: 'Elbay Hotel',
    intro:
      'A modern hotel website and guest reservation platform designed to provide a polished booking experience while showcasing rooms, suites, amenities, and hotel services.',
    points: [
      'Built with Next.js, React Motion, and Tailwind CSS.',
      'Developed responsive pages for room and suite showcases, amenities, services, and hotel information.',
      'Built an intuitive reservation interface for selecting check-in/check-out dates and managing booking flows.',
      'Implemented smooth animations and page transitions using React Motion.',
      'Developed a responsive and reusable UI system with Next.js and Tailwind CSS.',
      'Integrated location, contact, FAQ, and guest information sections into the booking experience.',
      'Optimized the interface for fast navigation and consistent experiences across desktop and mobile devices.',
    ],
    images: [
      '/elbey hotel/1.png',
      '/elbey hotel/2.png',
      '/elbey hotel/3.png',
      '/elbey hotel/4.png',
      '/elbey hotel/5.png',
      '/elbey hotel/6.png',
      '/elbey hotel/7.png',
    ],
    techStack: [
      { name: 'Next.js', image: '/icons/next.png' },
    ],
    link: '#',
    logo: '/logos/elbay.png',
    color: '#FFC66D',
    created: '2025',
  },
  {
    name: 'Hotel Manager',
    intro:
      'A full-stack hotel reservation platform designed to provide a polished booking experience while managing rooms, availability, reservations, and hotel information.',
    points: [
      'Built with Next.js, NestJS, MongoDB, React Motion, and Tailwind CSS.',
      'Developed responsive pages for rooms, suites, amenities, services, and hotel information.',
      'Built an intuitive reservation workflow for selecting check-in/check-out dates and managing bookings.',
      'Developed backend APIs with NestJS for reservations, room data, availability, and booking workflows.',
      'Designed MongoDB data models for rooms, reservations, and hotel-related data.',
      'Implemented smooth animations and page transitions using React Motion.',
      'Developed reusable and responsive UI components with Next.js and Tailwind CSS.',
      'Integrated location, contact, FAQ, and guest information into the booking experience.',
      'Optimized the platform for fast navigation and consistent experiences across desktop and mobile.',
    ],
    images: [
      '/hotel manager/1.png',
      '/hotel manager/2.png',
      '/hotel manager/3.png',
      '/hotel manager/4.png',
      '/hotel manager/5.png',
      '/hotel manager/6.png',
    ],
    techStack: [
      { name: 'Next.js', image: '/icons/next.png' },
      { name: 'NestJS', image: '/icons/nest.js.png' },
      { name: 'MongoDB', image: '/icons/mongo.png' },
    ],
    link: '#',
    logo: '/logos/elbay.png',
    color: '#0F9AAD',
    created: '2025',
  },
];

export { programmingLanguages, categories, projects };
